import './styl/main.styl'
import './components/range-slider/range-slider.js'
import "./components/rate-button/rate-button.js"
import "./components/like-button/like-button.js"
import "./components/pagination/pagination.js"
import "./components/calendar/calendar.js"
import "./components/dropdown-facilities/dropdown-facilities.js"
import "./components/dropdown-guests/dropdown-guests.js"
import "./components/data-dropdown/data-dropdown.js"
import "./components/room-card/room-card.js"
